version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=212207190440.dkr.ecr.us-east-1.amazonaws.com/savings-fo
      - IMAGE_TAG=$ENVIRONMENT-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-12)
      - LATEST_IMAGE_TAG="$ENVIRONMENT-latest"
      - BUILD_TIME=$(date -R)
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION > version.txt
      - echo 'Build time :' $BUILD_TIME >> version.txt
      - echo 'IMAGE_TAG :' $IMAGE_TAG >> version.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:$LATEST_IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$LATEST_IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$LATEST_IMAGE_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"frontend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
